apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  labels:
    app: payments-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Database__ApplyMigrationsOnStartup: "true"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__VirtualHost: "/"
  Jwt__Issuer: "fcg-users-api"
  Jwt__Audience: "fcg"
